/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vector;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Properties;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public void saveProperties(String propertyFileName) {

        try (OutputStream output = new FileOutputStream(propertyFileName)) {

            Properties prop = new Properties();

            String team_name = "Vector";
            Integer team_number = 5233;

            // set the properties value
            prop.setProperty("team.name", team_name);
            prop.setProperty("team.number", team_number.toString());

            // save properties to project root folder
            prop.store(output, null);

            System.out.println(prop);

        } catch (IOException io) {
            io.printStackTrace();
        }
    }

    public void loadProperties(String propertyFileName) {

        try (InputStream input = new FileInputStream(propertyFileName)) {

            Properties prop = new Properties();

            // load a properties file
            prop.load(input);

            Integer team_number = Integer.parseInt(prop.getProperty("team.number"));
            // get the property value and print it out
            System.out.println(prop.getProperty("team.name"));
            System.out.println(team_number);

        } catch (IOException ex) {
            ex.printStackTrace();
        }

    }

    public static void main(String[] args) {
        String filename = "./app/src/main/resources/test.properties";
        // For Microsoft OS use '\' instead of '/'.
        App app = new App();
        System.out.println(app.getGreeting());
        app.saveProperties(filename);
        app.loadProperties(filename);
    }
}
